Update after github migration (#4)
* Updated recipes and release-package.yaml after migration to GitHub

* Updated release workflows after migration to GitHub

* Added '--ref ${{ github.ref }}' to the workflow dispatch command, to always ruun the workflow in the correct branch

* Fixed shumlub recipe miskate on git_url

* Added patch to ug-ants pyptoject.toml to make it compatible with Python >= 3.10

* Update license spelling in recipes

* Fixed ugants and ants testing

* Updated mule patches

* Added name and version to create-conda-package job name

* Minor updates to github run url

* Updated mule_utils_select.patch

* Minor update

* Deleted SVN_REALM unused env variable from check-new-releases workflow

diff --git a/.github/workflows/check-new-releases.yaml b/.github/workflows/check-new-releases.yaml
--- a/.github/workflows/check-new-releases.yaml
+++ b/.github/workflows/check-new-releases.yaml
@@ -1,5 +1,5 @@
 name: Check new releases
-# Check new releases of the packages inside the `packages/` directory from MOSRS.
+# Check new releases of the packages inside the `packages/` directory from MetOffic GitHub Organisation.
 # If any package has a new release, it triggers the `release-package.yaml` workflow.
 
 on:
@@ -10,7 +10,6 @@ on:
 env:
   RELEASE_WORKFLOW: release-package.yaml
   RELEASE_ORDER: '["shumlib", "mule", "ants"]'
-  SVN_REALM: '<https://code.metoffice.gov.uk:443> Met Office Code'
 
 jobs:
   get-packages:
@@ -38,61 +37,63 @@ jobs:
     outputs:
       release_json: ${{ steps.check-new-releases.outputs.release_json }}
     env:
-      GH_TOKEN: ${{github.token}}
+      GH_TOKEN: ${{ secrets.GH_TOKEN_METOFFICE }}
     permissions:
       actions: write
     steps:
       - name: Checkout source
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
         with:
           fetch-tags: true
           fetch-depth: 0
-
-      - name: Cache SVN auth for MOSRS
-        uses: access-nri/actions/.github/actions/cache-svn-auth@main
-        with: 
-          username: '${{ secrets.MOSRS_USERNAME }}'
-          password: '${{ secrets.MOSRS_PASSWORD }}'
-          realm: '${{ env.SVN_REALM }}'
-    
+        
       - name: Check new releases
         id: check-new-releases
         run: |
-          # For each package, check if a new release on MOSRS is present
+          # For each package, check if a new release on the MetOffice
+          # GitHub organisation is present
           release_json=[]
           for package in ${{ needs.get-packages.outputs.packages }}; do
             echo "Checking new release for $package ..."
-            latest_prop=($(bash packages/$package/get-latest-mosrs-version.sh))
-            latest_version=${latest_prop[0]}
-            latest_revision=${latest_prop[1]}
+            github_repo_url=$(
+              cat "./packages/$package/recipe/meta.yaml" \
+              | awk -F'git_url:' '/^[[:space:]]*git_url:/ {print $2}' \
+              | awk '{print $1}'
+            )
+            # Get repository in the format 'owner/repo' from the git_url
+            owner_repo="${github_repo_url#https://github.com/}"
+            owner_repo="${owner_repo%.git}"
+            latest_version=$(gh release view --repo $owner_repo --json tagName -q ".tagName")
+            if [ -z "$latest_version" ]; then
+              echo "::error::No releases found for '$package' in the GitHub repository '$owner_repo'."
+              exit 1
+            fi
             # If a tag in the format '<PACKAGE-NAME>-<VERSION>' is not already present,
             # add the latest version to the packages to release (release_json).
-            if [ -z "$(git tag -l $package-$latest_version)" ]; then
-              echo "Found new $package version on MOSRS:"
-              echo "  version: $latest_version"
-              echo "  revision: $latest_revision"
+            if [ -z "$(git tag -l "${package}-${latest_version}")" ]; then
+              echo "Found new '$package' version: $latest_version"
               # if the package is 'ugants', we can release it directly, otherwise we add it to the json
-              # to be released in a chain (shumlib -> mule -> ants)
+              # to be released in a chain of dependencies (shumlib -> mule -> ants)
               if [ "$package" == "ugants" ]; then
-                echo "Releasing ${package}-${latest_version} ..."
-                options="--field package_name=$package --field version=$latest_version --field revision=$latest_revision"
+                echo "Releasing '${package}-${latest_version}' ..."
+                options="--field package_name=$package --field version=$latest_version"
                 echo "Running '${{ env.RELEASE_WORKFLOW }}' workflow with the following options: '$options'"
-                gh workflow run ${{ env.RELEASE_WORKFLOW }} $options
+                gh workflow run ${{ env.RELEASE_WORKFLOW }} $options --ref ${{ github.ref }}
                 # We wait for the GitHub database to be updated with the latest triggered run
                 # and then we get the its URL
                 sleep 2 
                 run_url=$(gh run list --workflow ${{ env.RELEASE_WORKFLOW }} --limit 1 --json url --jq '.[0].url')
-                echo "::notice::Releasing ${package}-${latest_version}. Release workflow run: $run_url"
+                echo "::notice::Releasing '${package}-${latest_version}'. Release workflow run: $run_url"
               else
                 json=$(
-                  jq -n --arg pkg "$package" --arg rev "$latest_revision" --arg ver "$latest_version" \
-                  '{package_name: $pkg, version: $ver, revision: $rev}'
+                  jq -cn --arg pkg "$package" --arg ver "$latest_version" \
+                  '{package_name: $pkg, version: $ver}'
                 )
                 release_json=$(jq -c --argjson json_obj "$json" '. += [$json_obj]' <<< "$release_json")
-                echo "Added ${package}-${latest_version} to the packages to be released."
+                echo "Added '${package}-${latest_version}' to the packages to be released."
               fi
             else
-              echo "Latest $package version on MOSRS ('$latest_version') is already released."
+              echo "Latest $package version on GitHub ('$latest_version') is already released."
             fi
           done
           if [[ $release_json != '[]' ]]; then
@@ -100,19 +101,17 @@ jobs:
           else
             echo "No new packages to be released."
           fi
-          # Use a multi-line github output to safely set the json array as a github output
-          echo 'release_json<<EOF' >> $GITHUB_OUTPUT
-          echo "$release_json" >> $GITHUB_OUTPUT
-          echo 'EOF' >> $GITHUB_OUTPUT
+          # Set the release_json as a GitHub output to be used in the next job
+          echo "release_json=$release_json" >> $GITHUB_OUTPUT
 
   release-new-packages:
     name: Release new packages
     runs-on: ubuntu-latest
     needs: check-new-releases
     # Only run if there are new packages to release
-    if: ${{ needs.check-new-releases.outputs.release_json != '[]' }}
+    if: needs.check-new-releases.outputs.release_json != '[]'
     env:
-      GH_TOKEN: ${{github.token}}
+      GH_TOKEN: ${{ github.token }}
     permissions:
       actions: write
     steps:
@@ -122,21 +121,19 @@ jobs:
           # Order packages to release in the correct order (shumlib -> mule -> ants)
           release_json='${{ needs.check-new-releases.outputs.release_json }}'
           ordered_json=$(
-            jq -c 'def custom_order: ${{ env.RELEASE_ORDER }}; 
-            sort_by(.package_name as $pkg | (custom_order | index($pkg)) // (custom_order | length))
-            ' <<< "$release_json"
+            jq -c --argjson order '${{ env.RELEASE_ORDER }}' \
+              'sort_by(.package_name as $pkg | ($order | index($pkg)) // ($order | length))' \
+              <<< "$release_json"
           )
-          # Use a multi-line github output to safely set the json array as a github output
-          echo 'ordered_json<<EOF' >> $GITHUB_OUTPUT
-          echo "$ordered_json" >> $GITHUB_OUTPUT
-          echo 'EOF' >> $GITHUB_OUTPUT
+          # Set the json array as a github output
+          echo "ordered_json=$ordered_json" >> $GITHUB_OUTPUT
 
       - name: Release packages
         run: |
           echo "Releasing packages ..."
           options='--field release_json=${{ steps.order-packages.outputs.ordered_json }} --repo ${{ github.repository }}'
           echo "Running '${{ env.RELEASE_WORKFLOW }}' workflow with the following options: '$options'"
-          gh workflow run ${{ env.RELEASE_WORKFLOW }} $options
+          gh workflow run '${{ env.RELEASE_WORKFLOW }}' $options --ref ${{ github.ref }}
           # We wait for the GitHub database to be updated with the latest triggered run
           # and then we get the its URL
           sleep 2 
